# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e23dda520f1a8e0be3513990e691a1919587f5b9ac53933b67cd0a9e6aae214e66c89afd061ba42e4c57910ee0d16db8b5093b91fe2cceb07c09be460721b58e

test:
  secret_key_base: eb363a11422434a5c91ece55bcbd0c2a46c3c9610f9677a0d4c2d1bf9a9381b319b1f9e85907f90360adde81b4c27a680a65fcfbcfcefd1c5d78ee1f238bb98a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
